### ISSUE TITLE
[general need] Synchronisation between mia and capsul engine configuration is suboptimal, in V2

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#185]
Currently by going to File > Mia preferences it is possible to access the configuration settings for mia but also for capsul engine. In some cases this is completely redundant. 
The synchronisation between the two is currently sub-optimal. We are getting there but I think that a simple user would be lost at the moment.
**It would be necessary to have a perfect synchronisation (instantaneous) in both directions and that one adds or removes a configuration of module.**
Currently it is not all the time easy and faster to do.

In fact we did not invest too much effort in this direction because this duplication should disappear (keep only mia prefrence and a synchronisation invisible to the user would be made at each change, or keep only the display of the capsul engine). 

Another alternative, which goes in the direction of a reflection I had started and which I already mentioned, but which we never settled, would be to have a local or a remote mode of operation (soma-workflow does it, but we don't currently have a defined working mode in mia).
In this case, we could keep both.
The mia preferences would be keep for local use (where it is possible to test the validity of the config, which is currently done for spm and fsl) and capsul engine would be keep for remote use (where it may not be possible to check the config at the time of its definition). But this is beyond the scope of this ticket.

**Comment by servoz** [comment]
After a private discussion with @LStruber, it was decided :
- Until we can do better (perfect synchronisation between Mia's preferences and capsul engine configuration, this ticket), we comment out the CAPSUL part (including the `Edit CAPSUL config` button) in the Pipeline tab of the Mia's preferences.

The Mia's preferences synchronisation with capsul engine configuration works correctly now, but the opposite does not seem to be optimal. So, by commenting on the CAPSUL part, we won't have any more problems on that side. This is only a temporary solution, the best will be to synchronise properly in both directions.

**Comment by LStruber** [comment]
CAPSUL configuration has been commented in commit 0e8c820f601edb7185eab00ae4d564c2da856ab1. I let the ticket open until the synchronisation is completely fixed.

**Comment by denisri** [comment]
Do you have an example / test of bad sync between capsul and mi configs ?
Well, I have added the capsul config because we use it to edit some settings not managed by mia, and now we cannot any longer :/ What's the reason to remove it ? To avoid confusing users ? Can we rather, at least, make it available in admin mode (since this mode exists, let's use it)
Mia is based on Capsul, thus should not reimplement config settings that are already managed by capsul... In a more general way I think all the config should go in capsul config, and have only one config system (whatever GUI we use on top of it, it's another question). Then sync between configs will not be a problem at all anymore.

**Comment by servoz** [comment]
It take this ticket.

**Comment by servoz** [comment]
I found a little time to come back on this ticket.
- playing around fsl config, no system environment variables defined:
   - Nothing defined in Mia preferences:
![Screenshot from 2022-02-10 15-30-15](https://user-images.githubusercontent.com/37933899/153428967-1df99ab7-ffc0-4973-93cf-0b0e265bcde9.png)

  - So nothing is defined in capsul config (good synchronisation):
![Screenshot from 2022-02-10 15-30-32](https://user-images.githubusercontent.com/37933899/153429205-29888a74-08c9-4c7e-94b2-e0aeed744cc8.png)

  - In this case it is not possible to run a FSL process, this is normal.
![Screenshot from 2022-02-10 15-35-18](https://user-images.githubusercontent.com/37933899/153431303-a1a5264d-23bb-4d44-8f19-0c4eccf98361.png)

  - We define the FSL config file in Mia preferences, then we click on the OK button:
 ![toto](https://user-images.githubusercontent.com/37933899/153433074-05d4ae12-8e08-4dfe-8b96-afd9e3d53241.png)

  - If we go back to Mia preferences, then to capsul config (click in the Edit CAPSU config), we can see that the synchronisation has been done with capsul config:
![Screenshot from 2022-02-10 15-58-24](https://user-images.githubusercontent.com/37933899/153434145-06b38c6c-74a9-4032-9add-04d9d0db0aaf.png)

  - Moreover, the FSL processes are now running very well:
![Screenshot from 2022-02-10 16-00-23](https://user-images.githubusercontent.com/37933899/153434860-a898c2cb-e8c3-410c-be6d-646a78f3887d.png)

  - OK, let's say we don't want to do the configuration from Mia preferences but from capsul config. We start from no configuration for FSL:
![Screenshot from 2022-02-10 16-09-49](https://user-images.githubusercontent.com/37933899/153436436-1c81ce49-5f64-4ffa-8ef3-02904fa53baf.png)

  - We click on the Edit CAPSUL config, then we take the FSL tab. Nothing is defined in capsul config (good synchronisation):
![Screenshot from 2022-02-10 16-13-04](https://user-images.githubusercontent.com/37933899/153436932-3d0c3eba-1832-44cf-a8d5-ddf69daeb29c.png)

  - So we fill in the necessary fields (normally it seems to me that capsul automatically deducts the other parameters from the config field, but to avoid any error here the first two are filled in):
![Screenshot from 2022-02-10 16-21-05](https://user-images.githubusercontent.com/37933899/153438503-4a484446-b985-4780-912e-02f3ac929c57.png)

  - Then we click on the OK button:
![Screenshot from 2022-02-10 16-24-16](https://user-images.githubusercontent.com/37933899/153439126-17d4d164-7d11-4014-aaaa-5098cbef7635.png)

- So no synchronisation is done with Mia preference. Maybe after clicking on the OK button? Let's click on the OK button, then we exit the Mia preferences. Let's go back to the MIA preferences:

  - No synchronisation with Mia preferences was done:
![Screenshot from 2022-02-10 16-27-56](https://user-images.githubusercontent.com/37933899/153440226-068f806e-6639-44af-bad3-6e3b82c05f2e.png)

  - In fact even in capsul config the FSL config is not here:
![Screenshot from 2022-02-10 16-28-16](https://user-images.githubusercontent.com/37933899/153440579-8e95e34e-ee33-4b06-9e58-5b523039afbc.png)


Moreover it seems that the configuration is not kept when the GUI of capsul config is closed by clicking on the OK button because if, without leaving the Mia preferences, we click again on Edit CAPSUL config button, the FSL configuration is already lost. I will investigate this. However, I am away for a fortnight from tomorrow.

**Comment by servoz** [comment]
It's fixed for FSL.
If I remember well (I haven't retested yet) there was also a problem with matlab /spm.
I'll have a look later, in two weeks.

**Comment by servoz** [comment]
I start to see for Matlab/SPM.
Currently, 

-1 if nothing is defined in Mia preferences,
![rien](https://user-images.githubusercontent.com/37933899/156001809-7d142a4e-7d9f-4d3c-b8dc-79b4be5c447e.png)
we observe in the GUI of capsul config:
![matlab_rien](https://user-images.githubusercontent.com/37933899/156000292-ca7e6219-10ab-40b6-aae8-fe2d94eeaadc.png)
![spm_rien](https://user-images.githubusercontent.com/37933899/156000306-db47eb24-f90d-475e-881a-710bd7b9fc3f.png)
This looks good!

-2 Now if we define Matlab/SPM in mia preferences:
![mia_pref_matlab](https://user-images.githubusercontent.com/37933899/156001393-ab234bd1-d1a0-4d75-ac4d-627beeec15b9.png)
we observe in the GUI of capsul config:
![matlab](https://user-images.githubusercontent.com/37933899/156002550-26bde71c-0386-4abe-9cfb-426926def9a3.png)
![spm](https://user-images.githubusercontent.com/37933899/156002567-17569260-fde2-4673-944d-c0dcc4f63f17.png)
This looks good!

-3 Now if we define MCR/SPM standalone in mia preferences:
![mia_pref_mcr](https://user-images.githubusercontent.com/37933899/156003148-5dcbf678-6943-4a1e-ab9a-57da586b20ae.png)
we observe in the GUI of capsul config:
![matlabstandalone](https://user-images.githubusercontent.com/37933899/156003210-a74ad2c9-aa5f-4b48-b510-c851c5ab93ba.png)
![spmstandalone](https://user-images.githubusercontent.com/37933899/156003222-8551ab38-4928-4125-921f-ca3a98edd058.png)
This looks good for spm and wrong for matlab. Am I wrong? 
How should the value of the matlab executable field be in this case? /home/econdami/MATLAB/MATLAB_Runtime/v95 ?

**Comment by servoz** [comment]
In fact in capsul/study_config/config_modules/matlab_config.py, matlab_exec is defined as a File trait. So it is not possible actually to give here the path to the MCR (a Dir). So it is not possible to define the MCR path in the GUI of capsul config and it happens elsewhere in populse_mia, under the hood:

-> In populse_mia/software_properties.py (line 863):
```
       if capsul_config.get('use_spm', False):
            spm_dir = capsul_config.get('spm_directory')
            spm_standalone = capsul_config.get('spm_standalone')
            #TODO: I thing the following is wrong
            if spm_standalone:
                mcr = os.path.join(spm_dir, 'mcr', 'v713')
                if os.path.isdir(mcr) and os.path.isdir(spm_dir):
                    self.set_spm_standalone_path(spm_dir)
                    self.set_matlab_standalone_path(mcr)
                    self.set_use_spm_standalone(True)
                    self.set_use_matlab_standalone(True)
                    self.set_use_matlab(False)
            else:
                self.set_use_spm_standalone(False)
                if self.get_use_matlab():
                    self.set_spm_path(spm_dir)
                    self.set_use_spm(True)
                else:
                    self.set_use_spm(False)
```

As it is, it is not possible to synchronise capsul config with mia preferences, and worse, we have to use only mia pref to define the MCR path.

This is where I reach the limit of what I can do to close this ticket. I think the capsul config GUI should be able to accept a file or a directory for "executable" fields in the matlab tab. In this case, I'm not sure if "executable" is really suitable in the GUI ("path" would be better?).
Anyway, I need you to tell me what you have imagined on the subject. For now the whole thing works by chance for a bad reason (the hard-coded line: mcr = os.path.join(spm_dir, 'mcr', 'v713', see above)). If we want to put the capsul config GUI back in use we have to fix this problem. Then the synchronisation should work, with some modifications of the populse_mia codes.
I work in the with_capsul_config branch, where the Edit capsul config GUI is available.

Translated with www.DeepL.com/Translator (free version)

**Comment by servoz** [comment]
Of course! This is exactly what we did in mia pref. There is a matlab_exec and a matlab_standalone.
I respect your point of view, but, concerning matlab, whether it is an executable or not it is a file for an executable or a path in case of an MCR. It is more or less the same for SPM. In the case of standalone it is a file and in the case of "normal" SPM it is a directory ... 
What would be nice is to be able to define in the GUI either the matlab_exec or the matlab_standalone.

**Comment by servoz** [comment]
For SPM we use in both cases the "directory" field, so it's ok for the file (.sh) or the directory (in fact we add the .sh, under the hood, to the directory. But for matlab as you want to keep the notion of "executable" it's less obvious (for me we need the directory for the matlab executable and like for spm we could add, under the hood). With this, a "directory" field is enough instead of the "executable" field. But if you have another quick solution, I am interested.
For the moment I'm stuck until we know how to do it in the capsul side, to define the bin/matlab in the case of matlab or the path to the MCR in the case of the Compiler Runtime).
Also, I believe that it is necessary to make simple for lambda users. For us the notions of executable or MCR are important. But for a lambda user I am not sure that it is very important!

**Comment by denisri** [comment]
Why use the same field for matlab executable and the MCR ? If both can be used to run SPM, in a more general way it is not the same at all: you can run matlab alone, you can't run the MCR (I guess); one is a file, the other is a directory. Thus it seems simpler and clearer for me to use two config fields. However if you really want to, we can use the traits.Either type to allow a file or a directory, but I'm not convinced it its the best solution.
For me I would add a field matlab_mcr in capsul config, and if it were just for me I would completely remove it from MIA's config, to avoid redundancies, even if we keep MIA's GUI to edit it: its specialized GUI is obviously better than the generic GUI in Capsul, but it could allow to edit the same single config.
But as you like... Tell me if you want me to add the missing field in Capsul...

**Comment by servoz** [comment]
I think that MCR can be used without spm standalone (for example if we want to use compiled matlab codes, I have to look into it as soon as possible because I have matlab codes that I want to use without access to the source codes). But this is not the question.
if it's possible to define both, it's ok for me. it's just that i don't see yet exactly how it will work to find it (for spm it's easy, you check standalone or not, so you know exactly what it means) ...

**Comment by servoz** [comment]
I don't think it's a good idea to remove matlab_mcr from mia pref. The idea is to be perfectly synchronised, that is to say to be able to define the same things in mia pref and capsul config .... and for the moment to define the MCR we are obliged to go through mia pref, capsul config does not allow it.

**Comment by denisri** [comment]
> I don't think it's a good idea to remove matlab_mcr from mia pref

Why not ? Why is it a good thing to duplicate config options ?

> capsul config does not allow it.

that's exactly why I ask if I should add it in capsul config.

The reason I insist is, in addition to not liking duplicating things, that, for me MIA GUI should be a graphical interface to run Capsul pipelines, which we should normally be able to run also outside of the GUI, typically to run them on a computing resource, from a script or something else. Capsul may allow extensions like the features of MIAProcesses, databasing and provenance tracking etc. There are many things that were developed inside MIA's GUI (see the pipeline_management_tab.py which is both the GUI and in a large part also processing infrastructure. I would like to separate them, probably not in the short term, but we want, at the end, to be able to run any processing from the commandline `python -m capsul` (or what it becomes in the future). If we keep things separated like today, with a config for capsul, and another for MIA, a separate processing/run engine/loop, etc, we will not reach this goal, which is for me a deal-breaker for the whole project.

**Comment by servoz** [comment]
To tell the truth, if the GUI of capsul config works as well as mia pref, I have no problem to delete mia pref ... The actual problem goes beyond the synchronisation issue ... The problem is that capsul config doesn't work for the MCR. It's mandatory to use mia pref ... That's why we have unplugged the GUI of capsul config in mia pref in master actually ...

**Comment by denisri** [comment]
I have added the matlab `mcr_directory` field in capsul config.

**Comment by servoz** [comment]
Thanks @denisri ! I will see ASAP how to deal with ...

**Comment by servoz** [comment]
it is still not synchronised and it is still necessary to go through the mia prefs to update the GUI capsul config and thus allow to launch a calculation with SPM standalone.
But now I "only" have to manage the synchronisation in both directions, in populse_mia.
I maintain that having both definitions possible at the same time (one can never prevent a user from putting both!) is a source of error! which one to take?
I will try to manage this in populse_mia!

**Comment by denisri** [comment]
Hmmm... It is synchronized except that... 
* there is a bug somewhere in the capsul config GUI:
if I edit Capsul config, set matlab mcr_directory, and... wait a couple of seconds before validating, then the new value gets in the MIA settings. But if I click "OK" quickly, then the value is not updated. So I guess it lacks a forced validation of capsul GUI. I have to look at it.
* the other way, if I edit in MIA the value of matlab standalione path, then click "edit capsul config" *before validating MIA config*, then the value visible in capsul is the former one, because Capsul config is built from the state of MIA config, and not from the GUI, and MIA config is not changed until it is validated. We could hack this if needed, but as you said we should rather keep only one way to edit a given option, so in the long run we should rather hide the matlab/spm part of capsul config GUI.

**Comment by denisri** [comment]
The 1st way is fixed normally. The other way probably requires more work since it needs to take values in MIA config GUI, not in the config structure itself.

**Comment by servoz** [comment]
it is not synchronised.
Maybe we are not talking about the same thing? 
To me, synchronised means that we can edit the configuration in both directions. From mia pref to capsul config and from capsul config to mia pref. This is not the case for matlab/spm. 
I will look into this as soon as possible (I have already done it for FSL, vide supra)

**Comment by servoz** [comment]
I have a very hard time with this ticket. Most of the problems are mainly due to issue in the capsul config gui. I have started to plan some patches on a capsul branch. However, there are two things that if you had a solution, would save me from doing introspection in soma and capsul (which is interesting for the knowledge of the machinery, but is very time consuming !!!).

1- It is not possible to delete a parameter value. Let's say we want to switch from SPM to SPM standalone. We have as a starting point for matlab parameters:
![Screenshot from 2022-03-04 11-47-15](https://user-images.githubusercontent.com/37933899/156749817-67456e72-0700-4dee-a153-81200f327454.png)
We define the mcr_directory:
![Screenshot from 2022-03-04 12-59-36](https://user-images.githubusercontent.com/37933899/156759767-fd22d6d8-6231-458a-8dbd-b4024acd2831.png)

To be clean we want to remove the value of executable (there may be other reasons to remove the value of a parameter). 
![Screenshot from 2022-03-04 11-54-03](https://user-images.githubusercontent.com/37933899/156750556-dffefaa1-2fbb-451f-9378-6af1e823b902.png)
This is not possible. The old value automatically reverts (in this case we would like to revert to `<undefined>`)

2- It is not posssible to define mcr/standalone parameters for matlab/spm:
Let say we start with a empty config:

*matlab/spm case:*
![Screenshot from 2022-03-04 12-08-48](https://user-images.githubusercontent.com/37933899/156753000-8156e73d-5394-4b92-9faf-04b8d38059df.png)
We have the strange idea to change config from casul config gui :-):
![Screenshot from 2022-03-04 12-12-59](https://user-images.githubusercontent.com/37933899/156753523-f83a9b84-2d8e-491c-88bf-ece8bf3af19b.png)
![Screenshot from 2022-03-04 12-13-35](https://user-images.githubusercontent.com/37933899/156753536-9b396785-670a-4803-b53a-89d9b5d4a635.png)
We click on the OK button.
All is fine:
![Screenshot from 2022-03-04 12-19-49](https://user-images.githubusercontent.com/37933899/156754313-3291558b-154a-4ffb-9c54-6571cdfe678b.png)

*mcr/standalone case*
We start again from a empty config.
In  the capsul config gui:
![Screenshot from 2022-03-04 12-59-36](https://user-images.githubusercontent.com/37933899/156759946-a6395d1c-8292-4459-800f-6fec477885f1.png)
![Screenshot from 2022-03-04 12-24-05](https://user-images.githubusercontent.com/37933899/156755012-d8aaf558-8ee3-4f39-a9aa-0bb378a0ad96.png)
We click on the OK button, and we stay with a empty config in mia config.

In fact the issue here does not come from a synchronisation problem between capsul config and mia config, but rather from the capsul/soma side (well I think).
Indeed for matlab part we see in capsul/engine/module/matlab.py, introspection:
![Screenshot from 2022-03-04 12-37-52](https://user-images.githubusercontent.com/37933899/156756858-0b85ed59-91e4-4cc8-9365-910ee6ca49a3.png)
conf is not None and executable have the good value in controller object.
BUT for spm part, we see in capsul/engine/module/spm.py, introspection:
![Screenshot from 2022-03-04 12-46-10](https://user-images.githubusercontent.com/37933899/156757882-c0916375-77fc-445d-a745-54012e094d8a.png)
directory and standalone attributes are ok in the controller objetc but the conf is None ... 
So we lost the values ... And the final result is:
![Screenshot from 2022-03-04 12-54-28](https://user-images.githubusercontent.com/37933899/156759058-3cf2f0d7-9157-4b1a-910e-06bdc13777a7.png)

It's a pretty painful ticket because before working on the synchronisation you have to debug the capsul/soma side !!!

**Comment by denisri** [comment]
1. It's not very intuitive I admit, but to reset the value you have to type in the field the string `<undefined>`: emptying the edit line will just cancel edition and get back to the older value. The Controller GUI will be redesigned anyway.
2. You have removed yourself (commented out, to be exact) the line which performed the sync:
    https://github.com/populse/populse_mia/commit/381dd59f03d5d7cbc9b347bed20b33b85d792913
    by commenting out the line:
```
         self.set_matlab_standalone_path(mcr_dir)
```
    you forbid setting into MIA the edited Capsul config option for matlab standalone path.
    When I uncomment this line, it works (again) for me.

**Comment by servoz** [comment]
for -1 I had seen that <undefined> allowed a reset, but I was hoping for something more intuitive. Ok let's keep it that way, especially if the gui controller needs to be redesigned!
for -2 yes I know I commented on this, but it seemed to me that the problem came from well before (as described in the previous post) the set_capsul_config method of the populse_mia.software_properties module...
Ok I'll look into it right away

**Comment by servoz** [comment]
Ok ... I'm sorry I was on something else and had already forgotten about the thread...

In fact for 2- the problem does not come from matlab but from spm (that's why I haven't uncommented `self.set_matlab_standalone_path(mcr_dir)` because before working on the synchronisation it is necessary that the data edited in the gui of capsul config are well available ....

Look  in my last post above I never mentioned matlab but spm ... 

To be very clear this is what we have when we pass trough the set_capsul_config method:

*engine_config have not the good value for spm:*
![Screenshot from 2022-03-04 15-56-35](https://user-images.githubusercontent.com/37933899/156786086-3c0f1b84-1185-4f77-90f6-1d23ce05d377.png)

*Same thing for the capsul_config object:*
![Screenshot from 2022-03-04 15-58-13](https://user-images.githubusercontent.com/37933899/156786385-d6a5234d-dbe9-4f22-ba14-0dc971234905.png)

**Comment by servoz** [comment]
By the way, if I uncomment s`elf.set_matlab_standalone_path(mcr_dir)` it doesn't change anything on the result. This is not surprising because the edition of the spm parameters is not preserved...

**Comment by servoz** [comment]
The good question is why we lost the edited spm standalone parameters ?

**Comment by servoz** [comment]
Ok, I've already spent a lot of time on this ticket. I can't understand why the spm standalone values are not kept in the capsul config engine after a `Edit CASPUL config` in mia preferences. Fortunately, the equivalent on the mia preferences side works correctly. Since the `Edit CAPSUL config` button is no longer connected in the master branch of populse_mia, I think the best thing to do is to close this ticket !

**Comment by denisri** [comment]
I have done modifs to remove the use of the old study_config in this part, and to fix a number of issues in capsul/mia config sync. I continue to believe that Mia should take its config from capsul directly rather than duplicate everything in a different shape, because it's one of the (multiple) factors which make sync complex and "fragile", but I haven't worked on that side. In a general way, all of Mia config should be Capsul config modules, no more no less.

Anyway you have to understand that we have added the Capsul config GUI for a reasons, it's not a caprice: some config options do not exist in Mia and can be set only from Capsul config Gui, so we _need_ it. Putting it in a dead branch and closing the ticket is not an option. Plus, there is no modularity in Mia config. We need modularity.

**Comment by servoz** [comment]
Maybe you should be careful because if I didn't know you I would think that your last post is very arrogant...

Anyway, you must also understand that it is not possible to put things in Mia that do not work, or that will work one day ... Even if this thing, which does not work, is extremely important for you...

To say exactly and calmly what I think, I doubt we can go on like this for long. I can't spend my time trying to fix what's wrong with Mia after the changes, very important for you, that you made. This without any consultation, since you never have the time to have a meeting for a long time. It is true that we in Grenoble have plenty of time, when we are not skiing or playing tennis.

Ah just a last things ... since your last change, mia crash when we click in the `Edit CAPSUL config` button of the mia pref ... in addition to not working, it makes Mia crash. It's perfect!

**Comment by denisri** [comment]
It does not crash for me. Maybe things have not be updated for all projects ?
Anyway Mia is in development, we have different setups and environments, there are bugs (and not only on my side, but yes, like everyone, I sometimes make mistakes), things sometimes have to be fixed, and we do it. Now saying "this does not work, I remove it", I'm not very found of it. We clearly don't have the same objectives, and it's difficult to keep a common direction. Maybe too difficult. I also have heavy doubts on the project.

**Comment by servoz** [comment]
>> I also have heavy doubts on the project.

it is not impossible that this is the last thing we agree on.

**Comment by sapetnioc** [comment]
Don't you think it is time to have a meeting to talk about the future
direction of the project ? We worked a lot together with a good atmosphere
and mutual understanding. If this is no longer the case, we must find a
solution so that everyone can follow their objectives with serenity. Let's
not let an IT project completely ruin our human relations.

**Comment by denisri** [comment]
We can talk, sure, for me I'm not angry.

**Comment by servoz** [comment]
Planning a meeting is the best we can do at the moment, I think.

**Comment by servoz** [comment]
If we have defined a configuration for spm and spm standalone:
In software.properties.get_capsul_config() we pass through (l311 with_capsul_config branch):
```
       if use_spm:
            m = eeconf.setdefault('capsul.engine.module.spm',
                              {}).setdefault(spmconf['config_id'], {})
```

but  spmconf is not defined and raise exception:

```
Traceback (most recent call last):
  File "/data/Git_Projects/populse_mia/python/populse_mia/main.py", line 1313, in <module>
    main()
  File "/data/Git_Projects/populse_mia/python/populse_mia/main.py", line 812, in main
    config.get_capsul_engine()
  File "/data/Git_Projects/populse_mia/python/populse_mia/software_properties.py", line 389, in get_capsul_engine
    capsul_config = config.get_capsul_config()
  File "/data/Git_Projects/populse_mia/python/populse_mia/software_properties.py", line 313, in get_capsul_config
    {}).setdefault(spmconf['config_id'], {})
NameError: name 'spmconf' is not defined




```

**Comment by servoz** [comment]
I guess it is a typo and we can change by?:
 ```
if use_spm:
            m = eeconf.setdefault('capsul.engine.module.spm',
                              {}).setdefault('spm', {})

```

**Comment by servoz** [comment]
I had rather gone on the #191  ticket (which is long and tedious because it is about code cleaning ...). I'll come back to this ticket (#185) very quickly to try to understand what's wrong (tomorrow is already quite busy, but it's a priority for me). We'll keep in touch !

**Comment by denisri** [comment]
Well I don't have the same, and I don't know what's different.
All projects updated and on the same branches as you show.
When I erase the config files (`properties/config.yml` especially) and start populse_mia, **I don't have the message**:
```
An issue is detected in the Mia's configuration:
dictionary update sequence element #0 has length 1; 2 is required
Please check the settings in File > Mia Preferences > Pipeline ...
```
When I erase `process_config.yml` I have a very long log because all processes are re-scanned, and it should not matter here. When I only erase `config.yaml`, the output is:
```
$ python3 -m populse_mia

Checking the installed version for nipype, mia_processes and capsul ...

** mia is already using the current installed version of nipype, mia_processes and capsul for this station (1.7.0, 2.0.1-dev+dd90bd8 and 2.3.0, respectively)

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-dr144257'
```
nothing more at startup.
I open MIA preferences, go to admin mode, and click "edit config", I only have:
```
admin_hash: 60cfd1916033576b0f2368603fe612fb78b8c20e4f5ad9cf39c9cf7e912dd282
mia_user_path: /casa/host/src/populse/populse_mia/master
opened_projects:
- /tmp/temp_mia_project1q84smsi
source_image_dir: /casa/host/src/populse/populse_mia/master/python/populse_mia/sources_images
```
so at this stage I don't have any Capsul config at all.
You seem to have a remaining Capsul config. Where can it come from ? I don't know if this is the cause of the problem.
* When I restart populse_mia and edit again the config (without having changed anything else, and I have to re-type the admin password since I have not saved the config), I now have:
```
admin_hash: 60cfd1916033576b0f2368603fe612fb78b8c20e4f5ad9cf39c9cf7e912dd282
capsul_config:
  engine:
    global:
      capsul.engine.module.attributes:
        attributes:
          attributes_schema_paths:
          - capsul.attributes.completion_engine_factory
          - populse_mia.user_interface.pipeline_manager.process_mia
          config_environment: global
          config_id: attributes
          process_completion: mia_completion
  engine_modules:
  - nipype
  - fsl
  - freesurfer
  - matlab
  - spm
  - fom
  - python
  - afni
  - ants
mia_user_path: /casa/host/src/populse/populse_mia/master
opened_projects:
- /tmp/temp_mia_projectn3d5cxif
source_image_dir: /casa/host/src/populse/populse_mia/master/python/populse_mia/sources_images
```
* Then I go to the pipeline tab (of the preferences), everything is empty/unchecked (no need to upload a snapshot).
* I check "use matlab standalone", set the path for it: `/host/usr/local/spm12-standalone/mcr/v713` for me, check "use SPM standalone" and enter the path: `/host/usr/local/spm12-standalone`.
Click "OK" -> I get a warning popup for `MRIFileManager.jar` but otherwise OK. Nothing more in `stdout/stderr`.
* go again in File > Mia preferences > Tools tab, I click in Edit config:
```
admin_hash: 60cfd1916033576b0f2368603fe612fb78b8c20e4f5ad9cf39c9cf7e912dd282
auto_save: false
background_color: ''
capsul_config:
  engine:
    global:
      capsul.engine.module.attributes:
        attributes:
          attributes_schema_paths:
          - capsul.attributes.completion_engine_factory
          - populse_mia.user_interface.pipeline_manager.process_mia
          attributes_schemas: {}
          config_environment: global
          config_id: attributes
          process_completion: mia_completion
      capsul.engine.module.axon:
        axon:
          config_environment: global
          config_id: axon
          shared_directory: /casa/host/build/share/brainvisa-share-5.1
          user_level: 0
      capsul.engine.module.fom:
        fom:
          auto_fom: true
          config_environment: global
          config_id: fom
          fom_path: []
          input_directory: /tmp/temp_mia_projectn3d5cxif/data/raw_data
          output_directory: /tmp/temp_mia_projectn3d5cxif/data/derived_data
      capsul.engine.module.freesurfer:
        freesurfer:
          config_environment: global
          config_id: freesurfer
      capsul.engine.module.matlab:
        matlab:
          config_environment: global
          config_id: matlab
          mcr_directory: /host/usr/local/spm12-standalone/mcr/v713
      capsul.engine.module.nipype:
        nipype:
          config_environment: global
          config_id: nipype
      capsul.engine.module.spm:
        spm:
          config_environment: global
          config_id: spm
          directory: /host/usr/local/spm12-standalone
          standalone: true
      capsul_engine:
        uses:
          capsul.engine.module.afni: ALL
          capsul.engine.module.ants: ALL
          capsul.engine.module.attributes: ALL
          capsul.engine.module.axon: ALL
          capsul.engine.module.fom: ALL
          capsul.engine.module.freesurfer: ALL
          capsul.engine.module.fsl: ALL
          capsul.engine.module.matlab: ALL
          capsul.engine.module.nipype: ALL
          capsul.engine.module.python: ALL
          capsul.engine.module.spm: ALL
  engine_modules:
  - nipype
  - fsl
  - freesurfer
  - matlab
  - spm
  - fom
  - python
  - afni
  - ants
clinical_mode: false
control_V1: false
mainwindow_maximized: true
mainwindow_size:
- 0
- 0
matlab_standalone: /host/usr/local/spm12-standalone/mcr/v713
max_projects: 5
max_thumbnails: 5
mia_user_path: /casa/host/src/populse/populse_mia/master
mri_conv_path: ''
opened_projects:
- /tmp/temp_mia_projectn3d5cxif
projects_save_path: /casa/host/src/populse/populse_mia/master/projects
radio_view: true
source_image_dir: /casa/host/src/populse/populse_mia/master/python/populse_mia/sources_images
spm_standalone: /host/usr/local/spm12-standalone
text_color: ''
use_afni: false
use_ants: false
use_fsl: false
use_matlab: false
use_matlab_standalone: true
use_spm: false
use_spm_standalone: true
user_mode: false
```
Both MIA and Capsul configs have been updated.
* I go to the Pipeline tab:
* I click on Edit Capsul config:
the GUI pops up, and displays the correct values.
* If I edit them to change matlab mcr_directory and spm_standalone directory, for instance, and validate, I see the new values in MIA.

So there is definitely something different beween your setup and mine....

The error message "An issue is detected in the Mia's configuration" is issued when setting Capsul config values from the dictionary of the previously existiing config, so there is probably something wrong left in your config, but I don't understand what nor where it comes from since you have erased your config before starting...
